// @ts-check
// Entrada do addon Vulpus: primeiro o núcleo, depois os sistemas (cada um se registra ao ser importado).
import "./core/comandos.js";
import "./core/teleporte.js";
import "./core/tela.js";
import "./sistemas/menu.js";
import "./sistemas/spawn.js";
import "./sistemas/casas.js";
import "./sistemas/voltar.js";
import "./sistemas/tpa.js";
import "./sistemas/caudas.js";
import "./sistemas/niveis.js";
import "./sistemas/identidade.js";
import "./sistemas/perfil.js";
import "./sistemas/ajustes.js";
import "./sistemas/hud.js";
import "./sistemas/leilao.js";
import "./sistemas/kitsune.js";
import "./sistemas/cla_dados.js";
import "./sistemas/cla_guerra.js";
import "./sistemas/cla_terreno.js";
import "./sistemas/ctf.js";
import "./sistemas/clas.js";
import "./sistemas/regras.js";
import "./sistemas/staff.js";
import "./sistemas/dono.js";
import "./sistemas/boas_vindas.js";
